# Generated by Django 4.1.3 on 2022-11-10 00:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoj_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khojmodel',
            name='input_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
