# Generated by Django 4.1.3 on 2022-11-11 04:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khoj_app', '0002_alter_khojmodel_input_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KhojModel',
            new_name='Khoj',
        ),
    ]
